### ISSUE TITLE
Filter sollen ihre Trefferzahlen anpassen, wenn anderer Filter gesetzt

### ISSUE THREAD

**Issue by mechtelm** [iqb-berlin/ize-studysearch#8]

**Comment by LisaPegelow** [comment]
WIE Filterfunktion

- innerhalb eines Filters mit ODER verknüpfen

- Filter untereinander mit UND (analog zu Google) verknüpfen

**Comment by ClaudiaNdf** [comment]
Scheint zu funktionieren :)
